version: "3.9"

services:
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    env_file:
      - ./postgres/.env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  api:
    container_name: django
    restart: unless-stopped
    build: ./app
    expose:
      - 8000
    env_file:
      - ./app/.env
    depends_on:
      - postgres
    command: python3 app.py

  bot:
    container_name: bot
    restart: unless-stopped
    build: ./bot
    command: python app.py
    env_file:
      - ./bot/.env
    volumes:
      - "./bot/logs:/bot/logs"
    depends_on:
      - api
    command: python3 app.py
