version: "3.9"

services:
  bot:
    container_name: bot
    # restart: unless-stopped
    build: ./bot
    command: python app.py
    env_file:
      - ./bot/.env
    volumes:
      - "./bot/logs:/bot/logs"
    depends_on:
      - codeforces_api
    command: python3 app.py
  
  celery:
    container_name: celery
    restart: unless-stopped
    build:  ./app
    env_file:
      - ./app/.env
    volumes:
      - ./app/logs:/app/logs
    command: celery -A celery_worker worker -B --loglevel=info -f logs/celery.log

  codeforces_api:
    container_name: codeforces_api
    restart: unless-stopped
    build: ./app
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
    depends_on:
      - postgres
      - celery
    command: python3 app.py

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - ./postgres/.env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379
